### ISSUE TITLE
Add support for CORS

### ISSUE THREAD

**Issue by ggoodman** [auth0/webtask-runtime#3] opened 2016-07-05 11:07 UTC
To enable a development workflow where a webtask is being run locally along-side another app on a different port, CORS rules apply and requests will fail.

See auth0/wt-cli#68

**Comment by santiagorp** [comment] 2016-08-08 14:06
CORS does not work yet on POST requests. Example request running directly from Node.js:

> **Request URL:**http://localhost:3000/query
> **Request Method:**OPTIONS
> **Status Code:**200 OK
> **Remote Address:**[::1]:3000
> ### Response Headers
> **Access-Control-Allow-Credentials:**true
> **Access-Control-Allow-Headers:**X-Requested-With,content-type
> **Access-Control-Allow-Methods:**GET, POST, OPTIONS, PUT, PATCH, DELETE
> **Access-Control-Allow-Origin:***
> **Allow:**POST
> **Connection:**keep-alive
> **Content-Length:**4
> **Content-Type:**text/html; charset=utf-8
> **Date:**Mon, 08 Aug 2016 13:**11:**46 GMT
> **ETag:**W/"4-oCQ57CKdi+DnSwwWAjkjEA"
> **X-Powered-By:**Express
> ### Request Headers
> **Accept:***/*
> **Accept-Encoding:**gzip, deflate, sdch
> **Accept-Language:**en-GB,en;q=0.8,es;q=0.6
> **Access-Control-Request-Headers:**accept, content-type
> **Access-Control-Request-Method:**POST
> **Cache-Control:**no-cache
> **Connection:**keep-alive
> **Host:**localhost:**3000
> **Origin:**null
> **Pragma:**no-cache
> **User-Agent:**Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36


When same application is running from a webtask using wt serve these are the headers:

> **Request URL:**http://localhost:**8080/query
> **Request Method:**OPTIONS
> **Status Code:**200 OK
> **Remote Address:**127.0.0.1:8080
> ### Response Headers
> **access-control-allow-headers:**accept, content-type
> **access-control-allow-methods:**POST
> **access-control-allow-origin:**null
> **access-control-allowcCredentials:**true
> **Connection:**keep-alive
> **Date:**Mon, 08 Aug 2016 13:14:12 GMT
> **Transfer-Encoding:**chunked
> ### Request Headers
> **Accept:***/*
> **Accept-Encoding:**gzip, deflate, sdch
> **Accept-Language:**en-GB,en;q=0.8,es;q=0.6
> **Access-Control-Request-Headers:**accept, content-type
> **Access-Control-Request-Method:**POST
> **Cache-Control:**no-cache
> **Connection:**keep-alive
> **Host:**localhost:**8080
> **Origin:**null
> **Pragma:**no-cache
> **User-Agent:**Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

As you can see the response headers in the second case correspond to the change from https://github.com/auth0/webtask-runtime/commit/1779c95ce44f9d3bf9e7f323422b9481d8e9413f. Thus the following code is never executed on POST application/json requests.

``` js
// Initialize CORS
app.use(function (req, res, next) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
    res.setHeader('Access-Control-Allow-Credentials', true);
    next();
});
```
As a consequence, the real request fails afterwards.

**Comment by santiagorp** [comment] 2016-08-09 17:41
Finally I managed to have my code working. 

CORS seems to be working for POST requests. The reason why the request was failing is a different one:
 POST requests are not being captured by my router.post methods from express.

Example of methods not being invoked when express is running on a webtask
```js
router.post("/myRoute", function(req, res, next) {
  // Code not reachable even if req.method is POST
});
```

However this works:
```js
router.use("/myRoute", function(req, res, next) {
  // This works, but then I have to filter req.method being only POST.
  // Otherwise I also get the OPTION requests when not running from a webtask.
});
```
So finally I wrote a [helper function](https://github.com/santiagorp/mongoBridge/blob/master/webtask/lib/helpers/requestHelper.js) which checks for this. It also retrieves the requestBody from the webtask context, as it is not available on the req.body anymore.

Still to be addressed the fact that we cannot specify custom headers for the preflight requests as they are all being set on https://github.com/auth0/webtask-runtime/commit/1779c95ce44f9d3bf9e7f323422b9481d8e9413f.

**Comment by ggoodman** [comment] 2016-08-11 12:43
@santiagorp we need to continue intercepting `OPTIONS` requests _before_ they hit webtask code to maintain parity with our cloud runtime. Our cloud runtime is composed of two main components: 1) a proxy that handles administrative api calls; and 2) a collection of sandbox runtimes to which executions are proxied.

In this set-up, CORS is handled at the proxy level and these requests are never delegated to the sandbox level. `webtask-runtime` needs to maintain this approach to avoid surprises when transitioning to the cloud runtime. It does, however look like there are some capitalization issues with the headers in the response and a typo as well.

**Comment by santiagorp** [comment] 2016-08-11 12:56
I think HTTP header names (not sure about values) are case insensitive. Anyhow, I think it is necessary to provide a way to specify additional custom headers or change the values of some of them: Examples: accept PATCH method or set a custom header like X-MyCompany-Token-Header-Name.

Regarding the issue of the router not being invoked on POST requests, do you have any explanation? I think that is related to the request body being processed by the runtime too, as it is available in the webtask context and not in the request itself anymore.

**Comment by santiagorp** [comment] 2016-08-11 14:58
As Geoff said, the response headers for OPTIONS requests are being replayed from the request itself, so the issue is not CORS related at all.

Thanks for your help!

**Comment by rwtombaugh** [comment] 2018-05-11 22:44
This is a duplicate of https://github.com/auth0/wt-cli/issues/68 so I'm closing it

**Closed by rwtombaugh** 2018-05-11 22:44 UTC
